[package]
name = "async-socks"
version = "0.1.0"
authors = ["Arsenii Lyashenko <arsenylyashenko.3@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.4", features = ["net", "tcp", "udp", "dns", "io-util"] }
thiserror = "1.0.9"
async-trait = "0.1.21"

[dev-dependencies]
tokio = { version = "0.2.4", features = ["net", "tcp", "udp", "dns", "io-util", "macros"]}
