on: [push, pull_request]

name: CI

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Cache cargo registry
              uses: actions/cache@v1
              with:
                  path: ~/.cargo/registry
                  key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-registry-
            - name: Cache cargo index
              uses: actions/cache@v1
              with:
                  path: ~/.cargo/git
                  key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-index-
            - name: Cache cargo build
              uses: actions/cache@v1
              with:
                  path: target
                  key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-build-target-
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable
                  override: true
            - run: useradd hyper -p '$1$n16MMBrH$ZFC82eemhUrQB6CfaGiX20'  # `proxy` password
            - run: danted -D -f .github/workflows/danted.conf
            - uses: actions-rs/cargo@v1
              with:
                  command: test
                  args: --all --all-features
    rustfmt:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install toolchain
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: nightly
                  override: true
                  components: rustfmt
            - name: cargo fmt
              uses: actions-rs/cargo@v1
              with:
                  command: fmt
                  args: --all -- --check
    clippy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - run: rustup component add clippy
            - uses: actions-rs/clippy-check@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  args: --all-targets --all-features -- -D warnings
